version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/zettelkasten
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - PINECONE_INDEX=${PINECONE_INDEX}
      - PINECONE_CLOUD=${PINECONE_CLOUD}
      - PINECONE_REGION=${PINECONE_REGION}
      - EMBEDDING_DIMENSION=${EMBEDDING_DIMENSION}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_API_KEY=${EMAIL_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
    depends_on:
      - mongo
      - redis
    networks:
      - zettelkasten

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=zettelkasten
    volumes:
      - mongo_data:/data/db
    networks:
      - zettelkasten

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - zettelkasten

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - zettelkasten

volumes:
  mongo_data:
  redis_data:

networks:
  zettelkasten:
    driver: bridge 